baseURL: "https://b.nymk.ru"
title: "Плюшка с кодом"
languageCode: "ru-RU"
defaultContentLanguage: "ru"
theme: "hugo-bear"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: ""

minify:
  disableXML: true

# Отключаем навигационное меню
menu:
  main:
    - identifier: tutorials
      name: "Инструкции"
      url: "/tutorials/"
      weight: 2

languages:
  ru:
    languageName: "Русский"
    contentDir: content
    weight: 1

outputs:
  home:
    - HTML
    - RSS

# Отключаем таксономии (теги и категории)
disableKinds: ["taxonomy", "term"]

pagination:
  pagerSize: 10

params:
  env: production
  description: "Блог Кости о IT и других движухах"
  keywords: [блог, IT, программирование, разработка, код]
  author: "Костя"
  
  # Логотип блога
  label:
    icon: "pie.svg"
    iconHeight: 30
  
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false
  images: ["🧸"]

  profileMode:
    enabled: false

  homeInfoParams:
    Title: "Привет, %username%! 👋"
    Content: |
              Я Костя, и это мой блог. Тут буду постить свои движухи по IT и не только. Если хочешь кайфануть от айтишки — залезай!

  # socialIcons disabled

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  
  cover:
    hiddenInList: false
    hiddenInSingle: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true
  x:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true 
  mainSections: ["posts"] 