baseURL = "https://b.nymk.ru/"
languageCode = "ru"
title = "Ням Ням"
theme = "PaperMod"

# Важные настройки для GitHub Pages
canonifyURLs = true
relativeURLs = false

[pagination]
  pagerSize = 10

sectionPagesMenu = "main"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    # disableHLJS = true # to disable highlight.js
    # disableFingerprinting = true
    favicon = "<link / abs url>"
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    apple_touch_icon = "<link / abs url>"
    safari_pinned_tab = "<link / abs url>"

  [params.label]
    text = "Ням Ням"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

  # profile-mode
  [params.profileMode]
    enabled = false # needs to be explicitly set
    title = "Добро пожаловать!"
    subtitle = "Мой блог о еде и жизни"
    imageUrl = "<title or url>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

  # home-info mode
  [params.homeInfoParams]
    Title = "Привет! 👋"
    Content = "Добро пожаловать на мой сайт о еде, рецептах и не только!"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/your_channel"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/nyamka10"

[menu]

  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Посты"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Обо мне"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Контакты"
    url = "/contacts/"
    weight = 4

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/nyamka10"
    weight = 5
    params = { icon = "github" }

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
[markup]
  [markup.highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # style = "github"

