baseURL = "https://nyamka10.github.io/"
languageCode = "ru"
title = "Мой блог"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Блог"
    url = "/posts/"
    weight = 1

